### ISSUE TITLE
please support rc1

### ISSUE THREAD

**Issue by ghost** [BCJTI/ng2-cookies#11]

**Comment by carcamano** [comment]
Hi @iloveyo123u1 !

I'm using it on Angular2-RC1. What's happening to you?

**Comment by devansdev** [comment]
this._cookie
Cookie {}

this the Cookie object in rc1.
do we need to configure anything on system.config.js?

this is the error I can see;
 Property \'set\' does not exist on type \'Cookie\'.'

**Comment by ghost** [comment]
thanks all very much
it's running

**Comment by ghost** [comment]
please close the issues

:)
