### ISSUE TITLE
Set Cookie Options? (HttpOnly, Secure, etc)

### ISSUE THREAD

**Issue by andyrue** [BCJTI/ng2-cookies#16]
Is there a way to set various options like 'HttpOnly' and 'Secure' on a cookie with this library?

**Comment by henrymyers** [comment]
I just submitted a pull request adding support for the 'secure' flag. https://github.com/BCJTI/ng2-cookies/pull/19

The 'HttpOnly' flag can't be set in Javascript.

**Comment by carcamano** [comment]
PR accepted and published. Thanks @henrymyers
