### ISSUE TITLE
Unable to implement in ionic 2 project

### ISSUE THREAD

**Issue by josx** [BCJTI/ng2-cookies#17]
great work on ng2-cookies!
I want to use it, but i get an error

```
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Same happen on this project:
https://github.com/urish/angular2-moment/issues/33

**Comment by josx** [comment]
Just made https://github.com/BCJTI/ng2-cookies/pull/18 to fix it up.
(i got the ideas from angular2-moment https://github.com/urish/angular2-moment/commit/b6bcd9b4eb1a9cc6f82d808ed0bf9a426fb25d3c )

**Comment by carcamano** [comment]
PR Acepted and publish. Gracias @josx
