### ISSUE TITLE
Error includeing Cookie

### ISSUE THREAD

**Issue by Lazarencjusz** [BCJTI/ng2-cookies#2]
I did like instruction says and have following error:
Error: XHR error (404 Not Found) loading http://localhost/ng2-cookies/ng2-cookies

**Comment by Bigous** [comment]
Try to use it in a project where Angular 2 is correctly working, like [mgechev/angular2-seed](http://github.com/mgechev/angular2-seed).
This library only works under Angular2.

**Comment by abedurftig** [comment]
Hi Bigous, I have my own project where Angular2 is correctly working. It's based on the Angular2 Quickstart code. I get the same issue as  Lazarencjusz. Cannot find a solution anywhere in the web. Do you have any other hints? Thanks.

**Comment by carcamano** [comment]
@abedurftig IDK Angular2 Quickstart deeply but looking angular.io it seems a Javascript project.

ng2-cookies is a Typescript lib and you have to run it in a Typescript project, try to use it with [mgechev/angular2-seed](http://github.com/mgechev/angular2-seed).

Good luck!

**Comment by nebiljabari** [comment]
If it can help I resolved the issue changing the target indicated in the Read Me and if it's relevant I also use the Angular 2 Quickstart

In `systemjs.config.js` :
`map: {'ng2-cookies': 'npm:ng2-cookies'}` instead  `map: {'ng2-cookies': 'vendor/ng2-cookies'}`
