### ISSUE TITLE
Get all attributes of object Cookie

### ISSUE THREAD

**Issue by fernandocode** [BCJTI/ng2-cookies#25]
It is possible to get value `expires`or `create`from a cookie with this library? 
- If yes. How should this be done? 
- If not. Is possible add this functionality the this library?

This information of print for example:

> ![cookie](https://cloud.githubusercontent.com/assets/3801304/19493087/0eb2a834-9558-11e6-9ef3-6663baea5b94.png)

**I noticed is only possible with the library to get the value of the `Content`attribute of the print.**

**Comment by Tyxz** [comment]
To get the expiration date from a cookie as it is, it is not possible with JavaScript.
It should be possible to add an expiration date as a key value pair.
You could use this library to add two cookies. One for the value, the other with the expiration date.
