### ISSUE TITLE
Cookie not null

### ISSUE THREAD

**Issue by kabsila** [BCJTI/ng2-cookies#29]
When i set cookie with
Cookie.delete('cookname'); or Cookie.set('cookname', null);

cookie become to string 'null' not null value.

**Comment by Bigous** [comment]
Ok, Delete should work, but when you set to null, it will be set to null.

A new version will be published today, see if it works for you, ok?

[]'s

**Comment by Bigous** [comment]
Closing due to the lack of activity.
