### ISSUE TITLE
No need for any configurations to make library work

### ISSUE THREAD

**Issue by poulad** [BCJTI/ng2-cookies#31]
I added the lib to a fresh Angular project generated using `angular-cli`. There was no need to change any configuration files as mentioned in `README.MD` file.

Issuing this command in the project root is enough to add the library:
`
npm install ng2-cookies --save
`

**Comment by Bigous** [comment]
All right, to this to work properly we should change the build to generate a [umd bundle](https://github.com/umdjs/umd).
We are very busy lately, but I'll find some time to do this.

**Comment by Bigous** [comment]
Hi @pouladpld, as I think all the people are using the new version of angular-cli, I think we can close this issue.
Thankyou very much
