### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by camilosampedro** [BCJTI/ng2-cookies#32]
I really liked your project and I was trying to use it through a [WebJar](http://www.webjars.org/npm) inside a Scala application. The page automatically create a `jar` ready to be used based on the `npm` package.

The problem with `ng2-cookies` is that when the WebJar is being deployed, it requires the package to have a [supported license](https://bintray.com/docs/api/#_footnote_1) (MIT is supported) and it is not finding any license file on GitHub or inside the `package.json`.

![captura de pantalla de 2017-01-13 13-56-32](https://cloud.githubusercontent.com/assets/8657866/21941722/2b8ab4b8-d998-11e6-8646-a189886ae3f4.png)

**Comment by Bigous** [comment]
Ok, it's in README.MD, but you sure got a point.
