### ISSUE TITLE
Delete  cookie with empty value

### ISSUE THREAD

**Issue by robert-cahoon** [BCJTI/ng2-cookies#36]
Is there a specific reason your class won't delete a cookie if it has no value? I have a use case to delete a cookie that has no value.

Cheers,
Rob C

**Comment by robert-cahoon** [comment]
Just an FYI - I've found a simple work around. I just update the target cookie with a value before removing.

Cheers
Rob C.

**Comment by Bigous** [comment]
There is a very good reason - it's a bug :D tks for reporting it. I'll work on it soon.
