### ISSUE TITLE
Uncaught Syntax: Unexpected token <

### ISSUE THREAD

**Issue by michaelburris** [BCJTI/ng2-cookies#4]
Hello. I'm getting the following error when I use your project in the standard angular 2 quick start demo.  I'm using the dependency in npm. My package.json file has `"ng2-cookies": "^0.1.4"` referenced.

`Uncaught SyntaxError: Unexpected token <`

I've tried importing the module in the index.html

`<script src="node_modules/ng2-cookies/ng2-cookies.js"></script>`

In the actual service component. I'm importing it as suggested in your readme.

```
import {Injectable} from 'angular2/core';
import {Cookie} from 'ng2-cookies/ng2-cookies';

@Injectable()
export class AuthenticationService {
  logoutUser() {
     let csrfcookie = Cookie.getCookie('csrftoken');
  }
}
```

I can't seem to fix the issue. Any help would be appreciated. Thank you!

**Comment by carcamano** [comment]
@michaelburris I recomend you to use a good and working base project to develop your application.

Try to use https://github.com/mgechev/angular2-seed
- git clone https://github.com/mgechev/angular2-seed
- cd angular2-seed
- npm install
- npm install ng2-cookies --save
- npm start

This should solve!
