### ISSUE TITLE
not working in safari

### ISSUE THREAD

**Issue by stephenlane** [BCJTI/ng2-cookies#48]
Hi there,

This does not seem to work in safari.

**Comment by Bigous** [comment]
Can you post your environment configuration and more details on what doesn't work?

Did you check if cookies are not blocked in your safari configuration?

try to open your safari console (in the web tools development) and type on console:
```javascript
document.cookie
document.cookie='wow=it works; expires=May 31 2018 23:59:59 GMT+09:00; path=/'
document.cookie
```
To see if the cookie browser api is working as expected... it should show the same string appended by '; wow=it works'

**Comment by stephenlane** [comment]
I ended up having to use document.cookie instead of the set function as it was not working on safari, both mac and ipad.

**Comment by Bigous** [comment]
@carcamano can you get this? I can't test any code on mac or ipad - sorry.

**Comment by carcamano** [comment]
@Bigous Sorry, I can't too :( 

Anyway I tested it on Safari for Windows and it works fine.

**Comment by stephenlane** [comment]
i had the issue with both chrome and safari on ipad. Had no issue with chrome on mac

**Comment by Bigous** [comment]
Tested on safari on windows and linux and worked for me too. I'm closing it. If someone else is having problem, please post it here so we can trak with someon that uses macOS.

**Comment by esoyke** [comment]
I am also experiencing this, ended up falling back to localstorage if cookie fails. 

  Safari 11.1, Mac OSX High Sierra 10.13.4
  ng2-cookies: ^1.0.12

**Comment by Bigous** [comment]
@sephh My brother :D can you get this one?
