### ISSUE TITLE
URI malformed error in getting all Cookies

### ISSUE THREAD

**Issue by maronaquillo** [BCJTI/ng2-cookies#55]
I'm getting this error when I use `Cookie.getAll()` but it works on`Cookie.get()`.
Sample Text: `Tōkyō-to`

**Comment by Bigous** [comment]
I'm sorry about the loooooooong delay.

This only can happen if you are trying to retrieve cookies with Cookie that were not stored with Cookie. If you are trying to do that, I suggest you to use UnmanagedCookie. It doesn't try to encode and decode names and values and it will probable work flawlessly to you.
