### ISSUE TITLE
documentation doesn't cover api

### ISSUE THREAD

**Issue by joefatora** [BCJTI/ng2-cookies#56]
Please update the examples to include the date, path and domain options. I will happily do this but can't readily figure out how to edit the wiki directly. Thanks!

**Comment by Bigous** [comment]
Wow @joefatora That would be very nice.

Could you try to do [this](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) and push a pull to the wiki?

[]'s

**Comment by joefatora** [comment]
Sure, thanks for the pointer 😄
