### ISSUE TITLE
Unable to store boolean value in cookie

### ISSUE THREAD

**Issue by deepakgd** [BCJTI/ng2-cookies#6]
If i tried to set cookie value as below

`Cookie.setCookie('isAuthenticated', true);`

I am getting this error:
`error TS2345: Argument of type 'boolean' is not assignable to parameter of type 'string'.`

How to fix this issue?

**Comment by carcamano** [comment]
@deepakgd 

It's correct. Cookie is a string separeted by semicolon. So if you wanna store a true value, you should store as string.

``` typescript
Cookie.setCookie('isAuthenticated', 'true');
```

**Comment by deepakgd** [comment]
Ya now I m storing like this only. Thank you
